language: python
python:
  - "2.7"
  - "3.3"
env:
  - DJANGO=1.5
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then pip install -q Django==$DJANGO --use-mirrors; fi
  - pip install -r requirements.txt --use-mirrors
script:
  - nosetests
