language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
env:
  - DJANGO=Django==1.5.9
  - DJANGO=Django==1.6.6
  - DJANGO=https://github.com/django/django/archive/stable/1.7.x.zip

install:
  - pip install $DJANGO --use-mirrors

before_script:
  - sh -c "if [ '$DJANGO' = 'Django==1.5.8' ]; then pip install django-discover-runner; fi"

script:
  - python runtests.py

matrix:
  exclude:
    - env: DJANGO=Django==1.5.9
      python: "3.3"
    - env: DJANGO=Django==1.5.9
      python: "3.4"
