language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
env:
  global:
    - PYTHONPATH=.
  matrix:
    - DJANGO=Django==1.5
    - DJANGO=Django==1.6
    - DJANGO=https://github.com/django/django/archive/stable/1.7.x.zip

install:
  - "pip install $DJANGO --use-mirrors"

before_script:
  - sh -c "if [ '$DJANGO' = 'Django==1.5' ]; then pip install django-discover-runner; fi"

script:
  - python testproject/manage.py test

matrix:
  allow_failures:
    - env: DJANGO=https://github.com/django/django/archive/master.zip
